# Generated by Django 5.2 on 2025-07-06 10:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_userquizresponse'),
    ]

    operations = [
        migrations.AddField(
            model_name='userquizresponse',
            name='attempted_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
