# Generated by Django 5.2 on 2025-07-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_userquizresponse_attempted_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('subject', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('exam', 'Exam Preparation'), ('interview', 'Interview Preparation')], max_length=20)),
            ],
        ),
    ]
